{'simulation': {'archetypes': {'spec': [{'lib': 'cycamore',
                                         'name': 'Enrichment',
                                         'path': ''},
                                        {'lib': 'cycamore',
                                         'name': 'FuelFab',
                                         'path': ''},
                                        {'lib': 'cycamore',
                                         'name': 'Reactor',
                                         'path': ''},
                                        {'lib': 'cycamore',
                                         'name': 'Sink',
                                         'path': ''},
                                        {'lib': 'cycamore',
                                         'name': 'Source',
                                         'path': ''},
                                        {'alias': 'agents_sink',
                                         'lib': 'agents',
                                         'name': 'Sink',
                                         'path': ''},
                                        {'alias': 'agents_source',
                                         'lib': 'agents',
                                         'name': 'Source',
                                         'path': ''}]},
                'control': {'dt': 5259692,
                            'duration': 222,
                            'startmonth': 10,
                            'startyear': 2019},
                'facility': [{'config': {'FuelFab': {'fill_commods': 'fillcommod',
                                                     'fill_size': 0.0,
                                                     'fiss_commods': 'low_enriched_uranium',
                                                     'fiss_size': 0.0,
                                                     'outcommod': 'fresh_triso',
                                                     'throughput': 5.370401580917203e+298,
                                                     'topup_commod': 'low_enriched_uranium',
                                                     'topup_pref': 1.0,
                                                     'topup_size': 0}},
                              'name': 'FuelFab'},
                             {'config': {'Reactor': {'assem_size': 0.0,
                                                     'cycle_step': 0,
                                                     'cycle_time': 0,
                                                     'fuel_incommods': 'fresh_triso',
                                                     'fuel_outcommods': 'used_fuel',
                                                     'n_assem_batch': 0,
                                                     'n_assem_core': 0,
                                                     'n_assem_fresh': 0,
                                                     'n_assem_spent': 1000000000,
                                                     'power_cap': 0,
                                                     'pref_change_commods': 'fresh_triso',
                                                     'recipe_change_commods': 'fresh_triso',
                                                     'refuel_time': 0}},
                              'name': 'Reactor'},
                             {'config': {'agents_source': {'capacity': 1e+200,
                                                           'commod': 'fillcommod',
                                                           'recipe_name': 'natural_uranium'}},
                              'name': 'ffsource'},
                             {'config': {'Enrichment': {'feed_commod': 'natural_uranium',
                                                        'initial_feed': 0,
                                                        'max_enrich': 1.0,
                                                        'max_feed_inventory': 8.014237006509849e+298,
                                                        'product_commod': 'low_enriched_uranium',
                                                        'swu_capacity': 8.841327291530666e+298,
                                                        'tails_assay': 0.003,
                                                        'tails_commod': 'tailcommod'}},
                              'name': 'Enrichment'},
                             {'config': {'agents_sink': {'capacity': 1e+299,
                                                         'in_commods': 'tailcommod'}},
                              'name': 'enrichsink'},
                             {'config': {'Sink': {'capacity': 7.900008204326458e+298,
                                                  'in_commods': 'used_fuel',
                                                  'max_inv_size': 6.362641884359467e+298}},
                              'name': 'Sink'},
                             {'config': {'Source': {'inventory_size': 3.397061027404884e+298,
                                                    'outcommod': 'natural_uranium',
                                                    'throughput': 6.385353646268481e+298}},
                              'name': 'Source'}],
                'recipe': [{'basis': 'mass',
                            'name': 'natural_uranium',
                            'nuclide': [{'comp': 0.00711, 'id': 'U235'},
                                        {'comp': 0.99289, 'id': 'U238'}]},
                           {'basis': 'mass',
                            'name': 'low_enriched_uranium',
                            'nuclide': [{'comp': 0.0493352862223478,
                                         'id': 'U235'},
                                        {'comp': 0.9506647137776522,
                                         'id': 'U238'}]},
                           {'basis': 'mass',
                            'name': 'used_fuel',
                            'nuclide': [{'comp': 0.007049405146067976,
                                         'id': 'U235'},
                                        {'comp': 0.9810063997658409,
                                         'id': 'U238'},
                                        {'comp': 0.0002663945797753129,
                                         'id': 'Pu238'},
                                        {'comp': 0.0058209186966296945,
                                         'id': 'Pu239'},
                                        {'comp': 0.002960918696629694,
                                         'id': 'Pu240'},
                                        {'comp': 0.001735459348314847,
                                         'id': 'Pu241'},
                                        {'comp': 0.0008276972898876565,
                                         'id': 'Pu242'},
                                        {'comp': 5.606972898876565e-05,
                                         'id': 'Am241'},
                                        {'comp': 0.00018169728988765647,
                                         'id': 'Am243'},
                                        {'comp': 2.386972898876565e-05,
                                         'id': 'Cm242'},
                                        {'comp': 7.116972898876566e-05,
                                         'id': 'Cm244'}]}]}}
